### ISSUE TITLE
Feat: 希望能添加 cityHash128 方法

### ISSUE THREAD

**Issue by ccforward** [XadillaX/bling_hashes#1]
现在 `index.js` 只对外暴露了 `city32` 和 `city64` 两个方法

![image](https://user-images.githubusercontent.com/2782664/42122443-87e4e050-7c74-11e8-9f50-d606678878d9.png)

希望能添加 `cityHash128` 封装后的暴露函数

**Comment by XadillaX** [comment]
1.2.0 released.
