### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by sankooc** [XadillaX/bling_hashes#3]
错误信息如下
<img width="1157" alt="屏幕快照 2019-07-02 上午10 59 48" src="https://user-images.githubusercontent.com/1072795/60479529-ba002d00-9cb8-11e9-92f0-d053bce2f914.png">
<img width="1274" alt="屏幕快照 2019-07-02 上午11 00 03" src="https://user-images.githubusercontent.com/1072795/60479552-d0a68400-9cb8-11e9-9ae8-8450a486f906.png">

系统osx node： v12.5.0  npm： 6.9.0

**Comment by XadillaX** [comment]
发布新版本（version: 2.0.0, tag: latest）完成
